### ISSUE TITLE
Change download folder

### ISSUE THREAD

**Issue by Just-Learned-It** [keshavbhatt/BingWall#14]
In the settings allow to change the folder where the wallpapers are downloaded.

**Comment by keshavbhatt** [comment]
wallpaper downloaded by app are considered as app data (since the app uses it later and track the files) hence stored in standard app data location and not user defined random path which may get un-accessible at anytime in future for undefined reasons and as the result the app will break. The current behavior is to prevent that. Currently used location is accessible with a single click and remain same everytime.
